2주차 조현상 과제
KMU-WINK/2020-02-Algorithm pull request #20
Opened 2020-11-18 10:42 UTC by hyeonsang010716

2020-11-20 09:08 UTC, sanglim00 reviewed
열심히 하는 모습 보기 좋네요 ^.^

2020-11-20 09:08 UTC, sanglim00 commented on 미로 탈출.py
> +            break
이 부분에서 while문 조건을 True라고 넣어줬는데
```
while(posX != N-1 & posY != M-1):
    try:
        if route[posX][posY+1] == '0':
            posX += 1
            cnt += 1

        else:
            posY += 1
            cnt += 1
    except:
        if posX == N:
            posY += 1
            cnt += 1
        else:
            posX += 1
            cnt += 1
```
이렇게 break되는 조건을 while문에 넣어주면 더 좋을 것 같아요 😄

2020-11-23 05:09 UTC, hyeonsang010716 commented on 미로 탈출.py
> +            break
감사합니다!

2020-11-29 14:47 UTC, Kim-tang2 requested changes
다시 풀리퀘스트 올려주세요~~

2020-11-29 14:47 UTC, Kim-tang2 commented on 성적이 낮은 순서로 학생 출력하기.py
> +sorted(p_list.keys())
p_list.keys()를 한 번 출력시켜보세요. 학생의 이름으로 정렬을 하는 것이 아닌 점수로 정렬하는 것입니다. 그리고 점수의 타입 또한 str일 것입니다. 문제를 다시 읽고 풀어보세요. 화이팅 ☺️

2020-11-29 14:47 UTC, Kim-tang2 commented on 위에서 아래로.py
> +print(sort_list)
print(' '.join(list(map(str, sort_list))))
이 코드를 써주면 대괄호 없이 출력할 수 있습니다. 😆
list(map(str, 리스트))으로 정수형 리스트를 문자형 리스트로 바꾸고
.join을 통해 리스트를 문자열로 바꿀 수 있습니다.

2020-12-01 02:47 UTC, merged